name: Test

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print current UTC time
        run: date -u
      - name: Get timestamp and format
        id: time
        run: |
          echo "run_time=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
      
      - name: Show the time
        run: echo "Triggered at ${{ steps.time.outputs.run_time }}"
